blank_issues_enabled: true
contact_links:
  - name: 📖 Axiom Documentation
    url: https://github.com/zAxn1e/axiom-hitbox#readme
    about: Explore the official documentation and API references.
  - name: 📜 Contributing Guidelines
    url: https://github.com/zAxn1e/axiom-hitbox/blob/main/CONTRIBUTING.md
    about: Learn about Axiom's design principles and contribution guidelines.
